name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install required dependencies directly but exclude macOS-specific ones on Linux
          pip install pynput keyboard mouse
          if [ "$(uname)" == "Darwin" ]; then
            pip install pyautogui
          else
            # On Linux, install PyAutoGUI without pyobjc
            pip install --no-deps pyautogui
            pip install python-xlib
          fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Check formatting with black
        run: black --check .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install required dependencies directly instead of using pip install -e .
          pip install pynput pyautogui keyboard mouse

      - name: Test with pytest
        run: |
          # Create basic test directory if it doesn't exist
          mkdir -p tests
          touch tests/__init__.py
          # Run any existing tests or a basic import test
          python -c "import src"
          if [ -d "tests" ] && [ "$(ls -A tests)" ]; then
            python -m pytest --cov=src tests/ --cov-report=xml
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
